version: "2"

services:
  nginx:
    image: nginx
    container_name: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "wordpress"
    ports:
      - "8080:80"
    networks:
      network:
        ipv4_address: 172.16.0.2

  wordpress:
    image: wordpress:5.1.1-php7.3-apache
    container_name: "wordpress"
    ports:
      - "8081:80"
    volumes:
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins:ro
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: hogehoge
      WORDPRESS_DEBUG: "true"
    depends_on:
      - "database"
    networks:
      network:
        ipv4_address: 172.16.0.3

  database:
    image: mariadb:10
    container_name: "database"
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: piyopiyo
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: hogehoge
    networks:
      network:
        ipv4_address: 172.16.0.4

volumes:
  db_data:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
